name: craft_element
version: 0.1.0
description: Source code elements for the Craft libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://craft-dart.github.io

environment:
  sdk: '>=1.21.0-any <2.0.0'

dependencies:
  craft_type:
    path: ../craft-type
  meta: ^1.0.4

dev_dependencies:
  test: ^0.12.0
