name: craft_type
version: 0.1.0
description: Type information for the Craft libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://craft-dart.github.io

environment:
  sdk: '>=1.22.0-any <2.0.0'

dev_dependencies:
  test: ^0.12.0
