name: craft_analyzer
version: 0.1.0
description: Source code analysis for the Craft libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://craft-dart.github.io

environment:
  sdk: '>=1.24.0-any <2.0.0'

dependencies:
  analyzer: ^0.30.0
  craft_element:
    path: ../craft-element
  craft_element_builder:
    path: ../craft-element-builder
  craft_type:
    path: ../craft-type
  meta: ^1.0.4

dev_dependencies:
  test: ^0.12.0
  craft_element_test:
    path: ../craft-element-test
